# -*- coding: utf-8 -*-
"""exemplo_24/06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qyBfHNB5YNqMiR281kcO-K9EmSUK3C7R
"""

#importação de bibliotecas
import numpy as np

#definindo as variáveis
A = 100
B = 50
xa = 0.1
xb = 0.3

#definir funções
def vazao(A,B):
  C = A + B
  return C
print("C= ", vazao(A,B))

def concentracao(A,B,xa,xb):
  x = (A*xa + B*xb)/C
  return x
print("x = ", concentracao())